### PR TITLE
Colorize directives ``.. code::`` and ``.. code-block::``

### LINKED ISSUE #413: Colorize code inside ``..code ::`` directives
The code currently only displayed as a literal block, but no syntax highlight is applied. 
I think we could re-use the doctest syntaxt highlight and apply it to the ``..code ::`` directive, too.

### PR DESCRIPTION
**Pull request by tristanlatr**
Fixes #413

### CODE REVIEW

**Comment by not-my-profile** [comment]
Can't these directives also be used with non-Python code?

**Comment by tristanlatr** [comment]
No not right now.

**Comment by tristanlatr** [comment]
To include a code bloc without colorization, just use `::`. I’ll add that to the docs.

**Comment by not-my-profile** [comment]
I meant that e.g. `.. code:: html` should not be colorized as Python.

**Comment by tristanlatr** [comment]
Currently it will.

**Comment by not-my-profile** [comment]
Yes we can add it later. What I meant was that this PR should check the argument of the directive and only highlight it as Python when there is no argument or the argument == "python". When the argument is sth else it should not be highlighted as Python.

**Comment by tristanlatr** [comment]
That would require more work to adopt such behavior. I’m unsure if that should be part of this PR.

**Review by glyph — APPROVED** [review]
This all looks good to me, assuming CI is happy I think we can land it.

**Comment by tristanlatr** [comment]
Thanks @glyph, I'll merge this PR and create a follow-up issue for other languages.

**Pull request merged**
