### PR TITLE
Fix name resolution for intersphinx links

### PR DESCRIPTION
**Pull request by adiroiban**
See #124 

The root problem is Documentable.expandName but I was not able to fix its implementation. 
See #125 for more details.

I went with a dirty hack.

I have also increased the release number, so once this is merged we can create a tag and release a new version.

### CODE REVIEW

**Comment by glyph** [comment]
@adiroiban - I want to say "add a test case for this" but somehow this just _increases_ coverage already? :)

**Comment by adiroiban** [comment]
I start writing unit tests for Documentable.expandName ... but I found out that I had no idea what is going on there and how to write a proper fix and proper tests for it.

with a previous branch I have added functional end-to-end tests by running pydoctor against Twisted trunk...so we do have tests for this change... just that they are not unit tests and not easy to follow.

so, I can write a unit tests for translate_identifier_xref ... but the problem is that I don't really know what is wrong here and how to write the docstring for the test

**Comment by glyph** [comment]
@mwhudson - any help?

**Comment by hawkowl** [comment]
Since this has 100% coverage, and it fixes an issue, and we don't really know any better way than yoloing it... sure, let's go with this.

**Pull request merged**
