### PR TITLE
Make Python2 and Python3 generate as-similar-as-possible outputs & add a script to see the differences

### PR DESCRIPTION
**Pull request by hawkowl**

### CODE REVIEW

**Comment by glyph** [comment]
@hawkowl is this dead, in favor of @mthuurne's work?

**Comment by mthuurne** [comment]
I think having the ability to easily diff between two runs of pydoctor is still useful.

Some of the changes are hard for me to evaluate though, since there are commit descriptions or unit tests that explain what issues they solve.

**Comment by moshez** [comment]
Is this still relevant given that we do not support 2.7 anymore?

**Comment by adiroiban** [comment]
I think that this can be closed as PY2 is no longer supported.

**Pull request closed without merging**
