### PR TITLE
fix: System has no method "warning"

### PR DESCRIPTION
**Pull request by ikalev**
See #92 for details.

### CODE REVIEW

**Comment by adiroiban** [comment]
Thanks for the patch

Changes look good, but the warning method is also used in pydoctor/astbuilder.py and implemented as

```
    def warning(self, type, detail):
        self.system._warning(self.current, type, detail)
```

so maybe we should also use self.system._warning here.


Now, I have no idea why this method is private.


I would argue that instead of using msg, we should make pydoctor.model.System._warning public by renaming it to pydoctor.model.System.warning

and also add a docstring :)

What do you think?

**Comment by ikalev** [comment]
This was my intuition too, but ``_warning()`` has a different signature. Looking at the calling code, the author clearly intended to call a method with a signature matching ``msg()``, not ``_warning()``.

**Comment by adiroiban** [comment]
True. Please update merge master in this branch and I will merge.

Sorry for the trouble... protected branched in GitHub are a PITA for non-team members.

**Comment by ikalev** [comment]
Done

**Pull request merged**
