### PR TITLE
Fixes the CI and other minor changes

### PR DESCRIPTION
**Pull request by tristanlatr**
Sorry I've break the CI yesterday. This correct the RST format as well as other minor refactor.

### CODE REVIEW

**Review by adiroiban — COMMENTED** [review]
Thanks for the cleanup.

The CI is still red.

How was it possible to merge with failing tests?

GitHub should be configured to prevent a merge if the CI is not green.

**Comment by tristanlatr** [comment]
I've added extra tests!

**Comment by tristanlatr** [comment]
@adiroiban  

> How was it possible to merge with failing tests?

I wasn't patient enough to wait the end of the workflow after having added some docs. I just merged to PR thinking the additional docs I've added were formatted OK. I wouldn't have done that if that wasn't docs we were talking about.

**Review by adiroiban — APPROVED** [review]
Thanks. 

I have enabled "auto-merge" functionality for this repo. 
I don't know why this is not enabled by default.

In this way, even if the tests are still running, you can queue the merge and it will be done after all the requirements are met.

**Pull request merged**
