### PR TITLE
Epydoc import

### PR DESCRIPTION
**Pull request by mthuurne**
This is a potential fix for #147.

I tried to cut away all the parts of epydoc that aren't used by pydoctor. Likely more can be cut away with in-depth analysis, but I ran out of obvious candidates. The full epydoc is over 27k lines of code; less than 9k remain after cutting. Please let me know if anyone sees other parts that can be removed.

I tested by running pydoctor's unit tests and running pydoctor to generate Twisted's documentation. Both pass with warnings, but the warnings don't seem to have anything to do with my changes.

### CODE REVIEW

**Comment by mthuurne** [comment]
The Travis build of the Twisted docs seems to be running a mixture of old and new code, which leads to `get_parser()` in `epydoc2stan` looking up the old name `epydoc.markup.epytext` and then not finding it because the module is now named `pydoctor.epydoc.markup.epytext`.

**Comment by mthuurne** [comment]
Is the graphviz support used by pydoctor? That is a fair amount of code with relatively low test coverage.

**Comment by glyph** [comment]
> Is the graphviz support used by pydoctor? That is a fair amount of code with relatively low test coverage.

I don't believe it is.

**Comment by glyph** [comment]
cc @mwhudson since he is the one who suggested this, more or less :)

**Comment by mwhudson** [comment]
Yeah happy with the idea, will try to look at it more on Monday. pydoctor
certainly doesn't deliberately use the graphvoz stuff...

**Comment by mthuurne** [comment]
I removed the graph generation code. There are now 6.2k lines of epydoc left, excluding tests.

**Comment by hawkowl** [comment]
I removed javadoc, since we don't use that. Epydoc and rst, we do kind of want, though.

**Comment by mwhudson** [comment]
yay!

**Comment by glyph** [comment]
*ZOMGGGGG*

Thank you @mthuurne for this amazing contribution!  And thank you @hawkowl for integrating it!

**Comment by glyph** [comment]
(Very excited for pydoctor to get some much-needed maintenance in the coming weeks!)

**Pull request merged**
