### PR TITLE
Improve UX by making the button text indicate the target state.

### PR DESCRIPTION
**Pull request by dreid**

### CODE REVIEW

**Comment by adiroiban** [comment]
Looks good!

Please also update the version number, so that after this is merged, we can create a tag and have the new version auto-published.

Thanks!

**Comment by glyph** [comment]
Hooray!

**Comment by glyph** [comment]
Since there are two positive comments already and the feedback was dealt with, landing.

**Comment by adiroiban** [comment]
don't forget that after landing, to create a tag so that it will be auto-released ... happy to get feedback about how we can make the release process easier :)

**Comment by glyph** [comment]
@adiroiban - pydoctor has fully automated releases?

**Comment by adiroiban** [comment]
@glyph I don't know what do you expect from a fully automated release... but if you push a new tag, travis-ci will run the tests and publish if on pypy . This was done in #115  and is briefly documented here https://github.com/twisted/pydoctor#releasing-a-new-package :)

**Comment by glyph** [comment]
@adiroiban That is more or less _exactly_ what I would expect from a fully automated release :).

**Comment by glyph** [comment]
Thanks very much for doing that!  I can't wait until we have a similar thing for Twisted...

**Comment by adiroiban** [comment]
I have pushed a tag for 16.2.1 ... and is now in pypi

Travis-CI is a bit crazy as there is no dedicated job for the release/deployment so without webhooks it is just a big pile of hacks :(

**Pull request merged**
