### PR TITLE
Fix modules name clash and processing order

### LINKED ISSUE #287: Issues in --introspect-c-modules
Hello,

I'm trying to generate https://github.com/igraph/python-igraph API docs, which works great for the python part (expect a few Epytext tags). 

Here is a test command that tries to document C modules only. 

```
pydoctor \
            --project-name=python-igraph \
            --make-html \
            --html-output=./apidocs \
            --project-base-dir="$(pwd)" \
            --docformat=epytext \
            --introspect-c-modules \
            --intersphinx=https://docs.python.org/3/objects.inv \
            ./src/_igraph/attributes.*
adding module .../src/_igraph/attributes.c
adding module .../src/_igraph/attributes.h
writing html to ./apidocs using pydoctor.templatewriter.writer.TemplateWriter
starting ModuleIndexPage ...took 0.004017s
starting ClassIndexPage ...took 0.002942s
starting IndexPage ...took 0.005538s
starting NameIndexPage ...took 0.002279s
starting UndocumentedSummaryPage ...took 0.001610s
Generating objects inventory at ./apidocs/objects.inv
```

It does not generates anything.

Empty name index. 

Any clue?

### PR DESCRIPTION
**Pull request by tristanlatr**
Finally finish to fix #287. 

This actually fixes two things: 
It adds clear rules to deal with modules that have duplcate names:
- C-modules wins over regular python modules
 - Packages wins over modules

This PR will create conflicts with #484 since I refactor the unprocessed_modules to be a `Dict`, not a list or a set. This way, we can have a better control on duplicates. 

This also fixes https://github.com/twisted/pydoctor/issues/482 and https://github.com/twisted/pydoctor/issues/429 because the order of processing modules is not random anymore since we're using `OrderedDict`.

### CODE REVIEW

**Comment by not-my-profile** [comment]
I think it would be better to have solve these problems in multiple PRs. I think this PR does too much.

**Comment by tristanlatr** [comment]
Fixing the processing order is just a side effect of properly fixing #287. I don’t think it’s worth splitting this PR. Also there are lot of tests.

**Comment by adiroiban** [comment]
Thanks for the update.

maybe is better to have this reviewed by @not-my-profile 

I an very short on time and I am only doing reviews for this as a last resort.

The changes looks good to me.

So if @not-my-profile doesn't have time for a review, I will review and approve it.

**Comment by adiroiban** [comment]
and GitHub is so limited... if you are not a member of the team you can't review :(

**Comment by tristanlatr** [comment]
I’de like to have this PR merged soon to publish a new pydoctor release. @not-my-profile, could you leave an approval on the PR? Thanks

**Comment by not-my-profile** [comment]
Sorry I can't get the GitHub review to work. I want to review your changes without my initial commit.

**Comment by tristanlatr** [comment]
@not-my-profile important commits are https://github.com/twisted/pydoctor/pull/488/commits/c65d49840aafbd264f5798493ecde0c5a24ec6d5 and https://github.com/twisted/pydoctor/pull/488/commits/4f951d8b2f3e7b56ec8f2201af9d4c03c1b25440

**Comment by tristanlatr** [comment]
Thanks @not-my-profile, I guess we're good to merge that PR ?

**Pull request merged**
