### PR TITLE
Enable break-word for parameter names and function names

### PR DESCRIPTION
**Pull request by tristanlatr**
This small adjustment to the CSS makes long words (namely long parameter names or function names) take multiple lines (without hyphen) when there is no space left. 
The current behaviour is annoying because long names overlaps with documentation.

Example of annoyance: [configargparse.ArgumentParser](https://tristanlatr.github.io/ConfigArgParse/configargparse.ArgumentParser.html#__init__)

### CODE REVIEW

**Review by adiroiban — CHANGES_REQUESTED** [review]
Thanks. 

As a minor comment, consider updating the example project to include a long parameter name so that we can observe that this is ok.

I am not a CSS expert so I can't tell the side effects of this change.

Do we need to enable it in the "body". Maybe it should be enabled only for `.fieldArgContainer` 

As as major comment, I think that word-break should only be applied to `.fieldArgContainer`

**Comment by tristanlatr** [comment]
Thanks for the quick review @adiroiban 

> As as major comment, I think that word-break should only be applied to `.fieldArgContainer`

There is also the function names that could overlap with the documentation in the summary table. So at least it should be enable for `.fieldArgContainer` and also for `#splitTables > table tr td:nth-child(2)`. This is why I choose to apply it to the whole body regardless, but I'll revert that.

**Comment by tristanlatr** [comment]
> it should be enable for .fieldArgContainer and also for #splitTables > table tr td:nth-child(2)

It's now only enabled for the above selectors. 

Not sure where the mypy error comes from, though. It's probably a recent update in the `types-docutils` package.

**Review by adiroiban — APPROVED** [review]
Sorry for the delay.

I have no idea how to best fix this.

I think that this can be merged and if  later we found other ways to fix the long lines we can have a separate PR.

Thanks!

**Comment by tristanlatr** [comment]
We should be good :)

**Comment by tristanlatr** [comment]
@adiroiban should I merge this PR ?

Thanks

**Comment by adiroiban** [comment]
yes. I think that you can merge it.

as a general rule, if a PR is not reviewed in more than 1 week, I think that is safe to merge it.

as otherwise the project is blocked.

**Comment by tristanlatr** [comment]
> as a general rule, if a PR is not reviewed in more than 1 week, I think that is safe to merge it.

Hum,  they are PR opened for months now. I’m particularly thinking of #386 . I don’t want to merge something that did not reach a certain consensus before, but at the same time I’m getting tired of waiting an approval, cause we can always do better. I’m sorry if not all my PRs are as clean as this one. I’m not a professional developer, I just enjoy making pydoctor better and more recognized in the python documentation ecosystem. Anyway, I’m not sure what you exactly meant by « safe to merge it », because if I don’t get an approval, it’s not socially safe (at least) to merge it.

**Comment by adiroiban** [comment]
You can ping me for "emergency review" .

But if we don't merge your request, the other way is for you to fork pydoctor ... and I don't think that will help anybody.

I am in a similar situation with Twisted in which my PR were not reviewed due to lack of interest for those features...but I had to deliver those features to the customers, so I ended up with a fork.

It makes my life harder when syncing with Twisted,  but there are also many other small bugfixed and improvements that are not in Twisted trunk.

**Comment by adiroiban** [comment]
If something break and people start complaining, then those people should dedicate more time doing code review for pydoctor.

So @tristanlatr  don't worry about the code quality or PR quality. I am very grateful that you are contributing! Thanks again!

**Comment by tristanlatr** [comment]
> So @tristanlatr don't worry about the code quality or PR quality.

Not sure our camarade @mthuurne feels the same way. 

> the other way is for you to fork pydoctor

I really don’t want to do that, I’m not doing this for clients. What I’m doing, nevertheless, is that I’m externalizing the ast builder and the python language model (see #430).

**Comment by tristanlatr** [comment]
> You can ping me for "emergency review" .

I’m a bit doubtful regarding the concept of emergency in this context, honestly. Nevertheless, some PRs are blocking the développement of others, namely #386. So if you have time to give your opinion regarding the status of this PR , it would be very appreciated.

**Pull request merged**
