### PR TITLE
Set up tox & travis for SUPER CI

### PR DESCRIPTION
**Pull request by hawkowl**
tox on py27 and pypy + pyflakes + .gitignore

### CODE REVIEW

**Comment by hawkowl** [comment]
@glyph could you enable Travis for this repo?

**Comment by hawkowl** [comment]
The failure is pyflakes, because there's pyflakes errors. should this be in allowed_failures for now?

**Comment by glyph** [comment]
allowed_failures seems like a good place to start for me

**Comment by mwhudson** [comment]
I stole this in stages and merged it, thanks!

**Comment by glyph** [comment]
woohoo

**Pull request closed without merging**
