### PR TITLE
Update list of projects using ``pydoctor``

### PR DESCRIPTION
**Pull request by tristanlatr**

### CODE REVIEW

**Comment by mthuurne** [comment]
Maybe we could also/instead link to the API docs of those projects? That's probably the thing that readers are interested in.

**Comment by tristanlatr** [comment]
> That's probably the thing that readers are interested in.

It's usually possible to find it in a few clicks...
Also I've linked to the home pages because not all projects configure `--project-url` inside their API docs.

**Comment by tristanlatr** [comment]
Can this be merged as is ?

**Comment by mthuurne** [comment]
Yes, I'll merge it now. It would be silly to not apply a clear improvement just because it could be made better.

**Pull request merged**
